### ISSUE TITLE
Improve error output

### ISSUE THREAD

**Issue by bartv** [inmanta/pytest-inmanta-lsm#334]
When a test case fails a diagnose runs and it will print out all the relevant information. However, by printing this all on a single line it becomes unreadable

![image](https://github.com/inmanta/pytest-inmanta-lsm/assets/10819/2cc5da70-25fe-458f-a112-0adbee474947)

The goal of this ticket is to properly format the message on multiple lines. This is a better version of the screenshot above:

```
INFO     pytest_****_lsm.wait_for_state:wait_for_state.py:160 Instance lifecycle got into bad state (rejected (version: 2)), 
    error: FullDiagnosis(
        failures=[], 
        rejections=[
            Rejection(
                instance_version=2, 
                model_version=None, 
                compile_id=UUID('fe6d6276-146c-4558-b03c-62b37ba7e7b0'), 
                errors=[
                    Error(
                        category=<ErrorCategory.runtime: 'runtime_error'>, 
                        type='****.ast.NotFoundException', 
                        message='variable t_vm not found', 
                        location=Location(
                            uri='/var/lib/****/server/environments/8404deea-3621-4bca-9076-6a612115f810/libs/athonet_mpn/model/domain/firewall/fortigate.cf', 
                            range=Range(start=Position(line=142, character=10), end=Position(line=142, character=27))))], 
                            trace=Traceback (most recent call last):
                                File "/opt/****/lib64/python3.9/site-packages/****/app.py", line 776, in app
                                    options.func(options)
                                File "/opt/****/lib64/python3.9/site-packages/****/app.py", line 611, in export
                                    raise exp
                                File "/opt/****/lib64/python3.9/site-packages/****/app.py", line 590, in export
                                    (types, scopes) = do_compile()
                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 81, in do_compile
                                    compiler.handle_exception(e)
                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 264, in handle_exception
                                    self._handle_exception_export(e)
                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 270, in _handle_exception_export
                                    raise exception
                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 262, in handle_exception
                                    self._handle_exception_datatrace(exception)
                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 274, in _handle_exception_datatrace
                                    raise exception
                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 76, in do_compile
                                    success = sched.run(compiler, statements, blocks)
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/scheduler.py", line 417, in run
                                    next.execute()
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 991, in execute
                                    raise e
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 987, in execute
                                    self._unsafe_execute()
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 981, in _unsafe_execute
                                    value = self.expression.execute(requires, self.resolver, self.queue_scheduler)
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/generator.py", line 162, in execute
                                    xc.emit(myqueue)
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1198, in emit
                                    self.block.emit(self, queue)
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/blocks.py", line 106, in emit
                                    raise e
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/blocks.py", line 103, in emit
                                    s.emit(resolver, queue)
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/assign.py", line 371, in emit
                                    reqs = self.value.requires_emit(resolver, queue)
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/generator.py", line 983, in requires_emit
                                    direct_requires = {rk: rv for (k, v) in direct for (rk, rv) in v.requires_emit(resolver, queue).items()}
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/generator.py", line 983, in <dictcomp>
                                    direct_requires = {rk: rv for (k, v) in direct for (rk, rv) in v.requires_emit(resolver, queue).items()}
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/__init__.py", line 512, in requires_emit
                                    requires.update({rk: rv for i in self.children for (rk, rv) in i.requires_emit(resolver, queue).items()})
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/__init__.py", line 512, in <dictcomp>
                                    requires.update({rk: rv for i in self.children for (rk, rv) in i.requires_emit(resolver, queue).items()})
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/variables.py", line 279, in requires_emit
                                    return self.requires_emit_gradual(resolver, queue, None, propagate_unset=propagate_unset)
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/variables.py", line 304, in requires_emit_gradual
                                    hook.schedule(resolver, queue)
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/__init__.py", line 319, in schedule
                                    self.instance.requires_emit(resolver, queue, propagate_unset=self.propagate_unset),
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/variables.py", line 89, in requires_emit
                                    requires[self.name] = resolver.lookup(self.full_name)
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1189, in lookup
                                    return self.resolver.lookup(name, root)
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1161, in lookup
                                    return self.parent.lookup(name, self.root)
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1189, in lookup
                                    return self.resolver.lookup(name, root)
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1099, in lookup
                                    return ns.lookup(name)
                                File "/opt/****/lib64/python3.9/site-packages/****/ast/__init__.py", line 367, in lookup
                                    return self.get_scope().direct_lookup(name)
                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1195, in direct_lookup
                                    raise NotFoundException(None, name, "variable %s not found" % name)
                                ****.ast.NotFoundException: variable t_vm not found (reported in implement athonet_mpn::domain::firewall::License using assign_license when true (/var/lib/****/server/environments/8404deea-3621-4bca-9076-6a612115f810/libs/athonet_mpn/model/domain/firewall/fortigate.cf:143:11))
                        )
                    )
                ]        
            )
        ]
    )
```

**Comment by sanderr** [comment]
The following reproduction and first steps towards a proposed solution may be a good start:

```python
FullDiagnosis(

        failures=[], 

        rejections=[

            Rejection(

                instance_version=2, 

                model_version=None, 

                compile_id=UUID('fe6d6276-146c-4558-b03c-62b37ba7e7b0'), 

                errors=[

                    Error(

                        category=<ErrorCategory.runtime: 'runtime_error'>, 

                        type='****.ast.NotFoundException', 

                        message='variable t_vm not found', 

                        location=Location(

                            uri='/var/lib/****/server/environments/8404deea-3621-4bca-9076-6a612115f810/libs/athonet_mpn/model/domain/firewall/fortigate.cf', 

                            range=Range(start=Position(line=142, character=10), end=Position(line=142, character=27))))], 

                            trace=Traceback (most recent call last):

                                File "/opt/****/lib64/python3.9/site-packages/****/app.py", line 776, in app

                                    options.func(options)

                                File "/opt/****/lib64/python3.9/site-packages/****/app.py", line 611, in export

                                    raise exp

                                File "/opt/****/lib64/python3.9/site-packages/****/app.py", line 590, in export

                                    (types, scopes) = do_compile()

                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 81, in do_compile

                                    compiler.handle_exception(e)

                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 264, in handle_exception

                                    self._handle_exception_export(e)

                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 270, in _handle_exception_export

                                    raise exception

                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 262, in handle_exception

                                    self._handle_exception_datatrace(exception)

                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 274, in _handle_exception_datatrace

                                    raise exception

                                File "/opt/****/lib64/python3.9/site-packages/****/compiler/__init__.py", line 76, in do_compile

                                    success = sched.run(compiler, statements, blocks)

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/scheduler.py", line 417, in run

                                    next.execute()

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 991, in execute

                                    raise e

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 987, in execute

                                    self._unsafe_execute()

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 981, in _unsafe_execute

                                    value = self.expression.execute(requires, self.resolver, self.queue_scheduler)

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/generator.py", line 162, in execute

                                    xc.emit(myqueue)

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1198, in emit

                                    self.block.emit(self, queue)

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/blocks.py", line 106, in emit

                                    raise e

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/blocks.py", line 103, in emit

                                    s.emit(resolver, queue)

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/assign.py", line 371, in emit

                                    reqs = self.value.requires_emit(resolver, queue)

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/generator.py", line 983, in requires_emit

                                    direct_requires = {rk: rv for (k, v) in direct for (rk, rv) in v.requires_emit(resolver, queue).items()}

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/generator.py", line 983, in <dictcomp>

                                    direct_requires = {rk: rv for (k, v) in direct for (rk, rv) in v.requires_emit(resolver, queue).items()}

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/__init__.py", line 512, in requires_emit

                                    requires.update({rk: rv for i in self.children for (rk, rv) in i.requires_emit(resolver, queue).items()})

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/__init__.py", line 512, in <dictcomp>

                                    requires.update({rk: rv for i in self.children for (rk, rv) in i.requires_emit(resolver, queue).items()})

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/variables.py", line 279, in requires_emit

                                    return self.requires_emit_gradual(resolver, queue, None, propagate_unset=propagate_unset)

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/variables.py", line 304, in requires_emit_gradual

                                    hook.schedule(resolver, queue)

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/statements/__init__.py", line 319, in schedule

                                    self.instance.requires_emit(resolver, queue, propagate_unset=self.propagate_unset),

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/variables.py", line 89, in requires_emit

                                    requires[self.name] = resolver.lookup(self.full_name)

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1189, in lookup

                                    return self.resolver.lookup(name, root)

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1161, in lookup

                                    return self.parent.lookup(name, self.root)

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1189, in lookup

                                    return self.resolver.lookup(name, root)

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1099, in lookup

                                    return ns.lookup(name)

                                File "/opt/****/lib64/python3.9/site-packages/****/ast/__init__.py", line 367, in lookup

                                    return self.get_scope().direct_lookup(name)

                                File "/opt/****/lib64/python3.9/site-packages/****/execute/runtime.py", line 1195, in direct_lookup

                                    raise NotFoundException(None, name, "variable %s not found" % name)

                                ****.ast.NotFoundException: variable t_vm not found (reported in implement athonet_mpn::domain::firewall::License using assign_license when true (/var/lib/****/server/environments/8404deea-3621-4bca-9076-6a612115f810/libs/athonet_mpn/model/domain/firewall/fortigate.cf:143:11))

                        )

                    )

                ]        

            )

        ]

    )
```

In practice the tab characters might be spaces, not sure.

**Comment by bartv** [comment]
@sanderr it might be worth a try to see what devtools does with it? or make it even renderable with devtools. pytest-inmanta-lsm is a dev dep anyway so something like devtools could be in its deps

**Comment by jptrindade** [comment]
```
DEBUG    inmanta.protocol.rest.client:client.py:118 Calling server GET http://172.25.20.2:8888/lsm/v1/service_inventory/bgp_neighbor/d4ae966c-a6ca-48bf-92af-9aa50c14226d/diagnose?version=2&rejection_lookbehind=0&failure_lookbehind=1
ERROR    pytest_inmanta_lsm.managed_service_instance:managed_service_instance.py:372 /home/jp/Inmanta/pytest-inmanta-lsm/src/pytest_inmanta_lsm/managed_service_instance.py:372 ManagedServiceInstance.wait_for_state.<locals>.get_bad_state_error
    d: FullDiagnosis(
        failures=[],
        rejections=[
            Rejection(
                instance_version=2,
                model_version=None,
                compile_id=UUID('21c5b59f-c108-41bf-90b1-2a257191877b'),
                errors=[
                    Error(
                        category=<ErrorCategory.runtime: 'runtime_error'>,
                        type='inmanta.ast.ExternalException',
                        message='Exception in plugin get_sirius_device_info',
                        location=Location(
                            uri=(
                                '/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/m'
                                'odel/service.cf'
                            ),
                            range=Range(
                                start=Position(
                                    line=31,
                                    character=0,
                                ),
                                end=Position(
                                    line=32,
                                    character=0,
                                ),
                            ),
                        ),
                    ),
                ],
                trace=(
                    'Traceback (most recent call last):\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 242, in '
                    'call_in_context\n'
                    '    value = self.plugin(*args, **kwargs)\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/plugins.py", line 495, in __call__\n'
                    '    value = self.call(*new_args, **new_kwargs)\n'
                    '  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/inman'
                    'ta_plugins/ir34/helpers/allocation_helpers.py", line 264, in func_or_cache\n'
                    '    allocated_value = func(\n'
                    '  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/inman'
                    'ta_plugins/ir34/__init__.py", line 586, in get_sirius_device_info\n'
                    '    codif_info = sirius.get_codif_information(service.port_ref)\n'
                    '  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/inman'
                    'ta_plugins/ir34/helpers/sirius.py", line 104, in get_codif_information\n'
                    '    results = flows.get_multihomed_codif_information(\n'
                    '  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/.env/lib64/pyth'
                    'on3.9/site-packages/pysirius/flows.py", line 378, in get_multihomed_codif_information\n'
                    '    results = resolver.resolve_ipxa(codif)\n'
                    '  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/.env/lib64/pyth'
                    'on3.9/site-packages/pysirius/flows.py", line 85, in resolve_ipxa\n'
                    '    raise exceptions.RefNotFoundException(f"Unable to find a Capacity CFS Instance with service i'
                    'd {codif}")\n'
                    'pysirius.exceptions.RefNotFoundException: Unable to find a Capacity CFS Instance with service id '
                    '1000023001\n'
                    '\n'
                    'The above exception was the direct cause of the following exception:\n'
                    '\n'
                    'Traceback (most recent call last):\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/app.py", line 776, in app\n'
                    '    options.func(options)\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/app.py", line 611, in export\n'
                    '    raise exp\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/app.py", line 590, in export\n'
                    '    (types, scopes) = do_compile()\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 81, in do_'
                    'compile\n'
                    '    compiler.handle_exception(e)\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 264, in ha'
                    'ndle_exception\n'
                    '    self._handle_exception_export(e)\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 270, in _h'
                    'andle_exception_export\n'
                    '    raise exception\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 262, in ha'
                    'ndle_exception\n'
                    '    self._handle_exception_datatrace(exception)\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 274, in _h'
                    'andle_exception_datatrace\n'
                    '    raise exception\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 76, in do_'
                    'compile\n'
                    '    success = sched.run(compiler, statements, blocks)\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/execute/scheduler.py", line 417, in ru'
                    'n\n'
                    '    next.execute()\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 289, in '
                    'execute\n'
                    '    raise e\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 285, in '
                    'execute\n'
                    '    self.function.resume(requires, self.resolver, self.queue, self.result)\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 129, in '
                    'resume\n'
                    '    self.function.call_in_context(arguments, kwargs, resolver, queue, result)\n'
                    '  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 262, in '
                    'call_in_context\n'
                    '    raise ExternalException(self.ast_node, "Exception in plugin %s" % self.ast_node.name, e)\n'
                    'inmanta.ast.ExternalException: Exception in plugin get_sirius_device_info (reported in get_sirius'
                    '_device_info(neighbor) (/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6'
                    '/libs/ir34/model/service.cf:32))\n'
                ),
            ),
        ],
    ) (FullDiagnosis)
INFO     pytest_inmanta_lsm.wait_for_state:wait_for_state.py:174 Instance lifecycle got into bad state (order_rejected (version: 2)), error: FullDiagnosis(failures=[], rejections=[Rejection(instance_version=2, model_version=None, compile_id=UUID('21c5b59f-c108-41bf-90b1-2a257191877b'), errors=[Error(category=<ErrorCategory.runtime: 'runtime_error'>, type='inmanta.ast.ExternalException', message='Exception in plugin get_sirius_device_info', location=Location(uri='/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/model/service.cf', range=Range(start=Position(line=31, character=0), end=Position(line=32, character=0))))], trace='Traceback (most recent call last):\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 242, in call_in_context\n    value = self.plugin(*args, **kwargs)\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/plugins.py", line 495, in __call__\n    value = self.call(*new_args, **new_kwargs)\n  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/inmanta_plugins/ir34/helpers/allocation_helpers.py", line 264, in func_or_cache\n    allocated_value = func(\n  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/inmanta_plugins/ir34/__init__.py", line 586, in get_sirius_device_info\n    codif_info = sirius.get_codif_information(service.port_ref)\n  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/inmanta_plugins/ir34/helpers/sirius.py", line 104, in get_codif_information\n    results = flows.get_multihomed_codif_information(\n  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/.env/lib64/python3.9/site-packages/pysirius/flows.py", line 378, in get_multihomed_codif_information\n    results = resolver.resolve_ipxa(codif)\n  File "/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/.env/lib64/python3.9/site-packages/pysirius/flows.py", line 85, in resolve_ipxa\n    raise exceptions.RefNotFoundException(f"Unable to find a Capacity CFS Instance with service id {codif}")\npysirius.exceptions.RefNotFoundException: Unable to find a Capacity CFS Instance with service id 1000023001\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/app.py", line 776, in app\n    options.func(options)\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/app.py", line 611, in export\n    raise exp\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/app.py", line 590, in export\n    (types, scopes) = do_compile()\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 81, in do_compile\n    compiler.handle_exception(e)\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 264, in handle_exception\n    self._handle_exception_export(e)\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 270, in _handle_exception_export\n    raise exception\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 262, in handle_exception\n    self._handle_exception_datatrace(exception)\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 274, in _handle_exception_datatrace\n    raise exception\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/compiler/__init__.py", line 76, in do_compile\n    success = sched.run(compiler, statements, blocks)\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/execute/scheduler.py", line 417, in run\n    next.execute()\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 289, in execute\n    raise e\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 285, in execute\n    self.function.resume(requires, self.resolver, self.queue, self.result)\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 129, in resume\n    self.function.call_in_context(arguments, kwargs, resolver, queue, result)\n  File "/opt/inmanta/lib64/python3.9/site-packages/inmanta/ast/statements/call.py", line 262, in call_in_context\n    raise ExternalException(self.ast_node, "Exception in plugin %s" % self.ast_node.name, e)\ninmanta.ast.ExternalException: Exception in plugin get_sirius_device_info (reported in get_sirius_device_info(neighbor) (/var/lib/inmanta/server/environments/3fa85f64-5717-4562-b3fc-2c963f66afa6/libs/ir34/model/service.cf:32))\n')])
FAILED
```
I got this output using:
```
            d = FullDiagnosis(**result.result["data"])
            LOGGER.error(msg=devtools.debug.format(d))
```
I still think it could be better, I'll explore a bit more
